FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Streamlit configuration
RUN mkdir -p ~/.streamlit
RUN echo "[client]\nshowErrorDetails = true\n[logger]\nlevel = info\n" > ~/.streamlit/config.toml

EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
